I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 819, in script
    "[Mdog] goes and grabs a water bottle off a nearby table."
KeyError: u'Mdog'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 819, in script
    "[Mdog] goes and grabs a water bottle off a nearby table."
  File "C:\Users\bflor\Downloads\renpy-7.1.3-sdk\renpy\ast.py", line 678, in execute
    renpy.exports.say(who, what, interact=self.interact, *args, **kwargs)
  File "C:\Users\bflor\Downloads\renpy-7.1.3-sdk\renpy\exports.py", line 1229, in say
    who(what, *args, **kwargs)
  File "C:\Users\bflor\Downloads\renpy-7.1.3-sdk\renpy\character.py", line 1018, in __call__
    what = what_pattern.replace("[what]", sub(what, translate=True))
  File "C:\Users\bflor\Downloads\renpy-7.1.3-sdk\renpy\character.py", line 1007, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Users\bflor\Downloads\renpy-7.1.3-sdk\renpy\substitutions.py", line 244, in substitute
    s = formatter.vformat(s, (), kwargs)
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 563, in vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 585, in _vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 646, in get_field
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 605, in get_value
KeyError: u'Mdog'

Windows-8-6.2.9200
Ren'Py 7.1.3.1092
Caineyes 1.0
Sun Feb 03 23:45:06 2019
